services:
    pgdatabase:
        image: postgres:13
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=ny_taxi
        volumes:
            - "$HOME/postgres_database_infra:/var/lib/postgresql/data:rw"
        ports:
            - "5433:5432"
        restart: always
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "8080:80"
        restart: always

    pgdatafeeding:
        build: .
        volumes:
            - "./taxiData:/app/taxiData"